### ISSUE TITLE
Merge ctree into master

### ISSUE THREAD

**Issue by martinju** [NorskRegnesentral/shapr#236]
It's finally time to bring ctree into master!

The ctree branch has quite many differences with the master, yet it should be fully documented and in good shape. Different parts of the branch are doing different things, so it should be possible to merge a few pieces at a time.

Preliminary PR-list
- [x] Update yaml-files and descriptions #238
- [x] Add `make_dummy` and `apply_dummy` functions #239
- [x] Update xgboost prediction/feature extraction functions #240 
- [x] Update all ctree functionality: `get_list_approaches`, `explain.combined`,  + Add specific ctree functions: `explain.ctree`, `prepare_data.ctree`, `sample_ctree`, `simulateAllTrees `. Add ctree scripts example_ctree_method.R, update vignette, readme and references. #241, #243

Workflow:
1. merge master into ctree to bring it up to date
2. duplicate master to a new branch "update_ctree_NAME" where NAME is an identifier of the update to be made.
3. Update "update_ctree_NAME" with stuff from the ctree branch.
4. Local install and restart + check 
5. make a PR from "update_ctree_NAME" into master.
6. Carefully check, then merge the PR, delete update_ctree_NAME and repeat step 1-6 with a new type of change until ctree and master have no differences.
7. Delete branch ctree

**Comment by martinju** [comment]
Fixed in #238 #239 #240 #241 #243.
